# Generated by Django 5.2.4 on 2025-07-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
        ('polls', '0003_remove_choice_name'),
    ]

    operations = [
    ]
