# Generated by Django 5.2.4 on 2025-07-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='채팅방 제목 (첫 번째 메시지 기반 자동 생성 또는 사용자 지정)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='채팅방 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 활동 시간')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('human', '사용자'), ('ai', 'AI')], help_text='메시지 발신자 (human 또는 ai)', max_length=10)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='메시지 생성 시간')),
                ('chat_room', models.ForeignKey(help_text='메시지가 속한 채팅방', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지들',
                'ordering': ['created_at'],
            },
        ),
    ]
